### ISSUE TITLE
OAuthButtons redirectUrlOverride prop isn't optional

### ISSUE THREAD

**Issue by xmaxcooking** [spoonjoy/redwoodjs-dbauth-oauth-web#1]
Hi! Just following the new tutorial and thought I'd add this here.

**Comment by arimendelow** [comment]
Sorry @xmaxcooking and @landrit, I totally missed this - can you provide a repro? It's optional as far as I can tell -
<img width="544" alt="Screenshot 2023-10-05 at 16 37 40" src="https://github.com/spoonjoy/redwoodjs-dbauth-oauth/assets/16390116/b75b9535-9ff3-4ac8-bfe9-c4ce6678559d">

**Comment by landrit** [comment]
Hi @arimendelow will have a look with @xmaxcooking on this :) we'll let you know. thank you

**Comment by arimendelow** [comment]
Sounds good!

**Comment by arimendelow** [comment]
hey @landrit and @xmaxcooking ! did yall get a chance to take a look?

**Comment by xmaxcooking** [comment]
hey @arimendelow sorry to reply so late. 

Here is a screenshot. 

![image](https://github.com/spoonjoy/redwoodjs-dbauth-oauth/assets/36244504/ea2c91a9-b972-44a6-921a-969517d0ddef)

To reproduce:
1. clone [redwoodjs-dbauth-oauth](https://github.com/spoonjoy/redwoodjs-dbauth-oauth)
2. go to the sample-oauth-project and upgrade @spoonjoy/redwoodjs-dbauth-oauth-web to >= 1.2.0
3. Open the loginPage where the OAuthButtons component is used.

**Comment by arimendelow** [comment]
aha @xmaxcooking, thanks for the repro!

there seems to be a difference in the way extracted optional properties are treated in `.tsx` and the generated `.d.ts` files - i'm not sure why, but it's easy enough to just make the extracted property optional as well: https://github.com/spoonjoy/redwoodjs-dbauth-oauth/commit/8781d4fa568c14dfcef97c324819cfb0765e748e

published as Web v1.2.3, and closing this as fixed! if you continue to run into this problem for some reason, feel free to reopen and let me know :)
